[app]
name = "xrandrs - Screen Resolution Adjuster"
version = "0.1"
author = "hitchhooker <tommi@niemi.lol>"
about = "Adjusts screen resolution based on configuration"

[[rules]]
min_aspect_ratio = 1.77
max_aspect_ratio = 1.78
min_width = 3840
zoom_level = "0.5x0.5"

[[rules]]
min_aspect_ratio = 1.32
max_aspect_ratio = 1.34
min_width = 1024
zoom_level = "1x1"
